---
- name: Integration of APIC-EM with Ansible
  hosts:  127.0.0.1
  connection: local
  gather_facts: no

  vars:
    foo: bar
    ansible_ssh_user: administrator
    enablepw: xxxxxxxx
    password: xxxxxxxx

  tasks:
  - name: Use APIC-EM controller to return a list of discovered devices
    apic_em_gather_facts:
     host: 192.0.2.1
     username: bob
     password: xxxxxxx

   - name: debug
     debug: msg="Target device {{ item }}"
     with_items: mgmtIp

  - name: Install the configuration file
    cisco_ios_install_config:
     URI: ftp://ftpuser:xxxxxx@10.255.40.101/sdn/lab_config_files/ios_config.cfg
     host:  "{{ item }}"
     username: admin
     enablepw: "{{ enablepw }}"
     password: "{{ password }}"
     debug: off
    with_items: mgmtIp

